### ISSUE TITLE
Take resource management out of the work chains.

### ISSUE THREAD

**Issue by yakutovicha** [nanotech-empa/aiida-nanotech-empa#83]
Based on experience, I would say that a better place to identify the required number of resources is probably outside of the work chain. The reason is straightforward: it is impossible to write a work chain that takes advantage of the peculiarities of a specific computational resource. Moreover, once the work chain is submitted, the user cannot control the resource use which might be dangerous.

Herein, my proposition would be:

1. Guarantee that work chains allow for fine tuning of resource requests.
2. Never manage the resources allocation automatically inside the work chain, but
3. Rather have tools to "propose" the resources and let the user modify the proposed values if they disagree with them.

@eimrek and @cpignedoli let me know if you have any other opinions. If you agree, please also let me know.

P.S. Happy to be the creator of the first-ever issue in this repo :)

**Comment by eimrek** [comment]
Hi @yakutovicha, i completely agree.

How i did with with the gaussian workchains was to allow user define any resources they want via metadata.options.resources, but if case they didn't, some sensible default was determined (which i almost always used), here: https://github.com/nanotech-empa/aiida-nanotech-empa/blob/ebb1f5e367935bcadee030cfe0597a3a9f33afe8/aiida_nanotech_empa/workflows/gaussian/common.py#L72

**Comment by cpignedoli** [comment]
I fully agree
