### ISSUE TITLE
Do not assign a label to a Kind if an atom has starting mag 0

### ISSUE THREAD

**Issue by cpignedoli** [nanotech-empa/aiida-nanotech-empa#92]
At present, if for the structure N-N-C-C-C-H-H we assign mag_per_site[0,0,0,0,0,0,0]
the structure will be stored as N1 N1 C1 C1 C1 H1 H1 

the good working case is:

with mag_per_site [1 0 -1 1 0 0 0]

we have

N1 N C1 C2  C H H

where N1 has starting mag 1
C1 has starting mag -1
C2 has starting mag 1

https://github.com/nanotech-empa/aiida-nanotech-empa/blob/54ba219a4ade08edbc889251280be95763c1366f/aiida_nanotech_empa/workflows/cp2k/cp2k_utils.py#L54

**Comment by yakutovicha** [comment]
@cpignedoli says that careful testing is required for this one.

**Comment by cpignedoli** [comment]
This should now be closed isn't it @yakutovicha ?

**Comment by yakutovicha** [comment]
> This should now be closed isn't it [@yakutovicha](https://github.com/yakutovicha) ?

yes, not sure where it was fixed, though...
